### ISSUE TITLE
HOW AM I SUPPOSED TO USE THE OG TEXTURE PACK?

### ISSUE THREAD

**Issue by polygoners1** [iArtie/DarkMode-V4#1]
When i got the ghostpower texture packs, i found out that they were .rar files. WHICH CANT BE USED ON TEXTURE LOADER! So if you can. Either give me a working .zip version of the texture pack, or show me how to do it (btw im using android 64)

**Comment by StupidIdiot1033** [comment]
https://drive.google.com/drive/folders/1_PXPpv4YQtjcKDY40ZRbenhstQJnylGz?usp=drive_link extract these and put them into the packs folder

**Comment by StupidIdiot1033** [comment]
idk why the original downloads are .rar files

**Comment by iArtie** [comment]
You need to extract the files with the "RAR" extension

**Comment by StupidIdiot1033** [comment]
yeah but i think you need another app or something to actually extract the .rar files

**Comment by polygoners1** [comment]
and then the next day texture workshop comes out and now i have the metal dark mode.
