### ISSUE TITLE
More texture bugs

### ISSUE THREAD

**Issue by Zacgamingpro1234** [iArtie/DarkMode-V4#10]
![image](https://github.com/user-attachments/assets/5b9e97d6-42ef-459a-a4e6-445d6a0d4a59)
![image](https://github.com/user-attachments/assets/75a651df-8600-4677-ac88-2a344ea0c2c8)
![image](https://github.com/user-attachments/assets/d72a5212-0562-48c5-800e-943b29f3a842)
The Globed Icon:
![image](https://github.com/user-attachments/assets/68083174-f1e4-4d4f-86fc-0c74bc8036d8)

In Geode, [Globed](https://geode-sdk.org/mods/dankmeme.globed2) and [GDDP - Demon Progression](https://geode-sdk.org/mods/minemaker0430.gddp_integration)

**Comment by iArtie** [comment]
The mod hasn't really been updated yet, but we're almost ready for the update! I leave you photos here so you can see that you don't have the current version ![Screenshot_20241224-125658.jpg](https://github.com/user-attachments/assets/ec59a0b3-8861-4a61-bee8-1cf8bed78fd9)

![Screenshot_20241224-125656.jpg](https://github.com/user-attachments/assets/7c06337d-d040-4169-97cf-604f34b604bc)

![Screenshot_20241224-125647.jpg](https://github.com/user-attachments/assets/c829e1c7-7856-458b-89d4-0028d937b0b1)
