### ISSUE TITLE
Does not apply with globed mod and texture loader buttons

### ISSUE THREAD

**Issue by TeahersAreStupid1234** [iArtie/DarkMode-V4#5]
https://i.imgur.com/h1FHudP.png

**Comment by iArtie** [comment]
Now it's fixed, download the texture pack again and try to see if it already works

**Comment by TeahersAreStupid1234** [comment]
nope it isnt

**Comment by TeahersAreStupid1234** [comment]
oh you mean the texture pack and not mod?

**Comment by TeahersAreStupid1234** [comment]
![image](https://github.com/iArtie/DarkMode-V4/assets/59105483/3201a620-bea6-4ea8-bbd4-be0661aee432)
geode icon is white not blue

**Comment by iArtie** [comment]
That's bc the mods parts from darkmode was released on METAL version, but is the same, just the color logo
