### ISSUE TITLE
Game Crashes When I Try to go Into Main Levels

### ISSUE THREAD

**Issue by sk11taddle** [iArtie/DarkMode-V4#6]
Not sure what would be causing this, but whenever I go into the main levels and try to either get off of stereo madness or play it, the game crashes. I put the crash log down below. I would provide a video with it happening, but the file's too large.

I also have found out that it crashes even if you just try to go back to the main menu.

[2024-07-10_05-08-32.log](https://github.com/user-attachments/files/16159290/2024-07-10_05-08-32.log)

**Comment by iArtie** [comment]
Can you send the video?

**Comment by sk11taddle** [comment]
[Geometry Dash 2024.07.10 - 05.08.30.14.zip](https://github.com/user-attachments/files/16169941/Geometry.Dash.2024.07.10.-.05.08.30.14.zip)

Here is one video its allowing me to put, I unfortunately had to compress it to zip. But it happens whenever i click the side arrows to scroll the main levels, back button or just try to play stereo madness

**Comment by iArtie** [comment]
Thanks! its menu shaders, maybe fixed in the next update

**Comment by sk11taddle** [comment]
Alright, thank you, its not too much of a problem since i dont really need to play the main levels but good to know its menu shaders causing the issue.

**Comment by iArtie** [comment]
Already fixed! go to geode and update darkmode v4 and test it and notice me if it doesnt crash anymore

**Comment by sk11taddle** [comment]
It doesn't crash now! That was a fast fix, thank you. :D
