### ISSUE TITLE
Latest version of Globed breaks some textures with texture pack

### ISSUE THREAD

**Issue by ghost** [iArtie/DarkMode-V4#7]
Some Icons and Gui are broken
https://github.com/user-attachments/assets/6b0ae146-2d72-4bb3-a16c-4f8bb9cadb00

**Comment by Celestemysterios** [comment]
can confirm ![Screenshot_20240716-123558.png](https://github.com/user-attachments/assets/31f0f416-2fb0-4ac3-a782-b63fb3ca8b0a)

![Screenshot_20240716-123547.png](https://github.com/user-attachments/assets/a4aa3784-5b73-4a25-b7dc-d07f7f724f1e)

**Comment by iArtie** [comment]
fixed
